Fixed indentation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,23 +40,23 @@ jobs:
           cd ./src
           env GOOS=linux GOARCH=arm64 go build -o updater-glmt6000 -trimpath -ldflags="-s -w"
 
-    - name: Check Required Secrets
-      run: |
-        missing_secrets=()
-    
-        if [ -z "${{ secrets.NSEC }}" ]; then
-          missing_secrets+=("NSEC")
-        fi
-    
-        # Add any other required secrets/variables here following the same pattern
-        if [ ${#missing_secrets[@]} -ne 0 ]; then
-          echo "::error::Missing required secrets: ${missing_secrets[*]}"
-          echo "Please set the following secrets in your repository settings:"
-          printf '%s\n' "${missing_secrets[@]}"
-          exit 1
-        else
-          echo "All required secrets are set"
-        fi
+      - name: Check Required Secrets
+        run: |
+          missing_secrets=()
+
+          if [ -z "${{ secrets.NSEC }}" ]; then
+            missing_secrets+=("NSEC")
+          fi
+
+          # Add any other required secrets/variables here following the same pattern
+          if [ ${#missing_secrets[@]} -ne 0 ]; then
+            echo "::error::Missing required secrets: ${missing_secrets[*]}"
+            echo "Please set the following secrets in your repository settings:"
+            printf '%s\n' "${missing_secrets[@]}"
+            exit 1
+          else
+            echo "All required secrets are set"
+          fi
 
       - name: Upload to Blossom
         id: upload
